### ISSUE TITLE
Relational vs. document based database

### ISSUE THREAD

**Issue by alexanderduring** [bazzline/php_component_database_file_storage#1]
Hi Stev,

have you made your mind up yet, if your file storage should follow a relational or a document based approach? I would prefer the document based approach, because it keeps it simple and easy to use and also the implementation would be much less complex.

FYI: This is an excerpt of the interface MongoDB defines:
- insert()
- update()
- find()
- findOne()
- remove()
- count()

Regards, 
Alex

**Comment by stevleibelt** [comment]
Hi Alex,

to keep the complexity low for the first iteration, I would go for "document based database".
Basically the idea is "no sql" flavored, meaning a simple "key-value-storage" whereas the value will be an data array.

For the interface naming, I am open for changes. Right now, it is pure [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) without a different dialect/naming.
I will definitely change my current "read/readList" approach to a more generic one, meaning no different method names for dealing with collections or single data sets.
For moving to the MongoDB-naming, I need to give this some thoughts.

**Comment by stevleibelt** [comment]
What do you think about the [current interface implementation](https://github.com/stevleibelt/php_component_database_file_storage/commit/bb11118b9ea13fecfcea67ea4bd5c5e0a3720cb8)?

**Comment by alexanderduring** [comment]
I am fine with that, thanks. :-)

Alex
